"""initial

Revision ID: 91138cde1d92
Revises: 
Create Date: 2026-06-26 15:24:13.741065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91138cde1d92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_activities_entity_number', 'activities', ['entity_number'], unique=False)
    op.create_index('ix_activities_nace_code_classification', 'activities', ['nace_code', 'classification'], unique=False)
    op.create_index('ix_denominations_entity_number', 'denominations', ['entity_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_denominations_entity_number', table_name='denominations')
    op.drop_index('ix_activities_nace_code_classification', table_name='activities')
    op.drop_index('ix_activities_entity_number', table_name='activities')
    # ### end Alembic commands ###
