"""covering_index_for_activities

Revision ID: ccbb0da58f44
Revises: bb4034a62770
Create Date: 2026-06-26 15:46:43.137682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccbb0da58f44'
down_revision: Union[str, Sequence[str], None] = 'bb4034a62770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_nace_code_classification'), table_name='activities', postgresql_ops={'nace_code': 'varchar_pattern_ops'})
    op.create_index('ix_activities_nace_code_classification', 'activities', ['nace_code', 'classification', 'entity_number', 'nace_version'], unique=False, postgresql_using='btree', postgresql_ops={'nace_code': 'varchar_pattern_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activities_nace_code_classification', table_name='activities', postgresql_using='btree', postgresql_ops={'nace_code': 'varchar_pattern_ops'})
    op.create_index(op.f('ix_activities_nace_code_classification'), 'activities', ['nace_code', 'classification'], unique=False, postgresql_ops={'nace_code': 'varchar_pattern_ops'})
    # ### end Alembic commands ###
